const express = require('express')
const cors = require('cors')
const user = require('./routes/user')
const comment = require('./routes/comment')
const video = require('./routes/video')
const extra = require('./routes/extra')
const studio = require('./routes/studio')
const bodyParser = require('body-parser')
const Profile = require('./routes/Profile')
const app = express()
const social = require('./routes/Facebook')
app.use(bodyParser.json())
app.use('/user', user)
app.use(cors())
app.use('/', extra)
app.use('/studio', studio)
app.use('/comment', comment)
app.use('/video', video)
app.use('/', social)
app.use('/', Profile)
module.exports = app
